name: Nagz
options:
  bundleIdPrefix: com.nagz
  deploymentTarget:
    iOS: "26.0"
  xcodeVersion: "16.0"

packages:
  KeychainAccess:
    url: https://github.com/kishikawakatsumi/KeychainAccess.git
    from: "4.2.2"
  GRDB:
    url: https://github.com/groue/GRDB.swift.git
    from: "7.0.0"
  NagzAI:
    path: ../nagz-ai

targets:
  Nagz:
    type: application
    platform: iOS
    sources:
      - path: Nagz
      - path: Assets.xcassets
        buildPhase: resources
      - path: PrivacyInfo.xcprivacy
        buildPhase: resources
    info:
      path: Nagz/Info.plist
      properties:
        CFBundleShortVersionString: $(MARKETING_VERSION)
        CFBundleVersion: $(CURRENT_PROJECT_VERSION)
        CFBundleIconName: AppIcon
        NSAppTransportSecurity:
          NSAllowsLocalNetworking: true
        UIApplicationSceneManifest:
          UIApplicationSupportsMultipleScenes: false
        UILaunchScreen:
          UIColorName: LaunchBackground
          UIImageName: LaunchLogo
          UIImageRespectsSafeAreaInsets: true
        UISupportedInterfaceOrientations:
          - UIInterfaceOrientationPortrait
          - UIInterfaceOrientationLandscapeLeft
          - UIInterfaceOrientationLandscapeRight
        UISupportedInterfaceOrientations~ipad:
          - UIInterfaceOrientationPortrait
          - UIInterfaceOrientationPortraitUpsideDown
          - UIInterfaceOrientationLandscapeLeft
          - UIInterfaceOrientationLandscapeRight
        ITSAppUsesNonExemptEncryption: false
    settings:
      base:
        DEVELOPMENT_TEAM: NEAY582ME4
        PRODUCT_BUNDLE_IDENTIFIER: com.nagz.app
        MARKETING_VERSION: "1.3.0"
        CURRENT_PROJECT_VERSION: "28"
        SWIFT_VERSION: "6.0"
        CODE_SIGN_STYLE: Automatic
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        ASSETCATALOG_COMPILER_GLOBAL_ACCENT_COLOR_NAME: AccentColor
        ASSETCATALOG_COMPILER_INCLUDE_ALL_APPICON_ASSETS: "YES"
        ENABLE_USER_SCRIPT_SANDBOXING: NO
    dependencies:
      - package: KeychainAccess
      - package: GRDB
      - package: NagzAI
    entitlements:
      path: Nagz/Nagz.entitlements
      properties:
        aps-environment: development

  NagzTests:
    type: bundle.unit-test
    platform: iOS
    sources:
      - path: NagzTests
    settings:
      base:
        SWIFT_VERSION: "6.0"
        GENERATE_INFOPLIST_FILE: YES
    dependencies:
      - target: Nagz
